sonar.projectKey=python-app
sonar.projectName=Python App
sonar.sources=app
sonar.tests=tests
sonar.exclusions=wsgi.py,app/Config.py,app/grpc_protos/**

sonar.python.coverage.reportPaths=coverage/coverage.xml

sonar.coverage.exclusions=\
  app/dao/**,\
  app/di_container.py,\
  app/communication/impl/**,\
  app/communication/factory.py,\
  app/repositories/clients/**,\
  app/repositories/routes/**,\
  app/services/routes/**,\
  app/services/clients/**,\
  app/services/adapters/**,\
  app/tasks/**,\
  app/controller_server.py,\
  app/repository_server.py,\
  app/service_server.py,\
  app/extensions.py,\
  wsgi.py,\
  app/Config.py

sonar.scm.disabled=true
