sonar.projectKey=python-app
sonar.projectName=arcana-cloud-python
sonar.sources=app,wsgi.py
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage/coverage.xml
sonar.coverage.exclusions=\
  app/dao/**,\
  app/di_container.py,\
  app/communication/impl/**,\
  app/repositories/clients/**,\
  app/repositories/routes/**,\
  wsgi.py,\
  app/Config.py
