# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x61rcana\"\x07\n\x05\x45mpty\"\x99\x02\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x15\n\rpassword_hash\x18\x04 \x01(\t\x12\x12\n\nfirst_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x13\n\x0bis_verified\x18\t \x01(\x08\x12\x11\n\tis_active\x18\n \x01(\x08\x12\r\n\x05phone\x18\x0b \x01(\t\x12\x12\n\navatar_url\x18\x0c \x01(\t\x12\x12\n\ncreated_at\x18\r \x01(\t\x12\x12\n\nupdated_at\x18\x0e \x01(\t\x12\x15\n\rlast_login_at\x18\x0f \x01(\t\"3\n\x11PaginationRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\"X\n\x12PaginationResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\"G\n\rErrorResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_USER']._serialized_start=34
  _globals['_USER']._serialized_end=315
  _globals['_PAGINATIONREQUEST']._serialized_start=317
  _globals['_PAGINATIONREQUEST']._serialized_end=368
  _globals['_PAGINATIONRESPONSE']._serialized_start=370
  _globals['_PAGINATIONRESPONSE']._serialized_end=458
  _globals['_ERRORRESPONSE']._serialized_start=460
  _globals['_ERRORRESPONSE']._serialized_end=531
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=533
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
