# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_protos import common_pb2 as common__pb2
from app.grpc_protos import repository_service_pb2 as repository__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in repository_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RepositoryServiceStub(object):
    """Repository Service - For Service → Repository communication

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryUsers = channel.unary_unary(
                '/arcana.RepositoryService/QueryUsers',
                request_serializer=repository__service__pb2.QueryUsersRequest.SerializeToString,
                response_deserializer=repository__service__pb2.QueryUsersResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/arcana.RepositoryService/GetUserById',
                request_serializer=repository__service__pb2.GetUserByIdRepositoryRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.GetUserByUsername = channel.unary_unary(
                '/arcana.RepositoryService/GetUserByUsername',
                request_serializer=repository__service__pb2.GetUserByUsernameRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.GetUserByEmail = channel.unary_unary(
                '/arcana.RepositoryService/GetUserByEmail',
                request_serializer=repository__service__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/arcana.RepositoryService/CreateUser',
                request_serializer=repository__service__pb2.CreateUserRepositoryRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/arcana.RepositoryService/UpdateUser',
                request_serializer=repository__service__pb2.UpdateUserRepositoryRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/arcana.RepositoryService/DeleteUser',
                request_serializer=repository__service__pb2.DeleteUserRepositoryRequest.SerializeToString,
                response_deserializer=repository__service__pb2.DeleteUserRepositoryResponse.FromString,
                _registered_method=True)
        self.ExistsByUsername = channel.unary_unary(
                '/arcana.RepositoryService/ExistsByUsername',
                request_serializer=repository__service__pb2.ExistsByUsernameRequest.SerializeToString,
                response_deserializer=repository__service__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.ExistsByEmail = channel.unary_unary(
                '/arcana.RepositoryService/ExistsByEmail',
                request_serializer=repository__service__pb2.ExistsByEmailRequest.SerializeToString,
                response_deserializer=repository__service__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.CountUsers = channel.unary_unary(
                '/arcana.RepositoryService/CountUsers',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=repository__service__pb2.CountResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arcana.RepositoryService/HealthCheck',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RepositoryServiceServicer(object):
    """Repository Service - For Service → Repository communication

    """

    def QueryUsers(self, request, context):
        """Query users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Get user by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """Get user by username
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Get user by email
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Create user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Update user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Delete user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExistsByUsername(self, request, context):
        """Check if username exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExistsByEmail(self, request, context):
        """Check if email exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountUsers(self, request, context):
        """Count users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RepositoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryUsers,
                    request_deserializer=repository__service__pb2.QueryUsersRequest.FromString,
                    response_serializer=repository__service__pb2.QueryUsersResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=repository__service__pb2.GetUserByIdRepositoryRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=repository__service__pb2.GetUserByUsernameRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=repository__service__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=repository__service__pb2.CreateUserRepositoryRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=repository__service__pb2.UpdateUserRepositoryRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=repository__service__pb2.DeleteUserRepositoryRequest.FromString,
                    response_serializer=repository__service__pb2.DeleteUserRepositoryResponse.SerializeToString,
            ),
            'ExistsByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.ExistsByUsername,
                    request_deserializer=repository__service__pb2.ExistsByUsernameRequest.FromString,
                    response_serializer=repository__service__pb2.ExistsResponse.SerializeToString,
            ),
            'ExistsByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ExistsByEmail,
                    request_deserializer=repository__service__pb2.ExistsByEmailRequest.FromString,
                    response_serializer=repository__service__pb2.ExistsResponse.SerializeToString,
            ),
            'CountUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.CountUsers,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=repository__service__pb2.CountResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arcana.RepositoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arcana.RepositoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RepositoryService(object):
    """Repository Service - For Service → Repository communication

    """

    @staticmethod
    def QueryUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/QueryUsers',
            repository__service__pb2.QueryUsersRequest.SerializeToString,
            repository__service__pb2.QueryUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/GetUserById',
            repository__service__pb2.GetUserByIdRepositoryRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/GetUserByUsername',
            repository__service__pb2.GetUserByUsernameRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/GetUserByEmail',
            repository__service__pb2.GetUserByEmailRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/CreateUser',
            repository__service__pb2.CreateUserRepositoryRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/UpdateUser',
            repository__service__pb2.UpdateUserRepositoryRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/DeleteUser',
            repository__service__pb2.DeleteUserRepositoryRequest.SerializeToString,
            repository__service__pb2.DeleteUserRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExistsByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/ExistsByUsername',
            repository__service__pb2.ExistsByUsernameRequest.SerializeToString,
            repository__service__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExistsByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/ExistsByEmail',
            repository__service__pb2.ExistsByEmailRequest.SerializeToString,
            repository__service__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/CountUsers',
            common__pb2.Empty.SerializeToString,
            repository__service__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.RepositoryService/HealthCheck',
            common__pb2.Empty.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
