# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# Constant for unimplemented method message (SonarQube S1192)
_METHOD_NOT_IMPLEMENTED = 'Method not implemented!'

from app.grpc_protos import common_pb2 as common__pb2
from app.grpc_protos import user_service_pb2 as user__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """User Service - For Controller → Service communication

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/arcana.UserService/GetUsers',
                request_serializer=user__service__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=user__service__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/arcana.UserService/GetUserById',
                request_serializer=user__service__pb2.GetUserByIdRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/arcana.UserService/CreateUser',
                request_serializer=user__service__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/arcana.UserService/UpdateUser',
                request_serializer=user__service__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/arcana.UserService/DeleteUser',
                request_serializer=user__service__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=user__service__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/arcana.UserService/ChangePassword',
                request_serializer=user__service__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=user__service__pb2.ChangePasswordResponse.FromString,
                _registered_method=True)
        self.VerifyUser = channel.unary_unary(
                '/arcana.UserService/VerifyUser',
                request_serializer=user__service__pb2.VerifyUserRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUserStatus = channel.unary_unary(
                '/arcana.UserService/UpdateUserStatus',
                request_serializer=user__service__pb2.UpdateUserStatusRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/arcana.UserService/HealthCheck',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User Service - For Controller → Service communication

    """

    def GetUsers(self, request, context):
        """Get users list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def GetUserById(self, request, context):
        """Get user by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def CreateUser(self, request, context):
        """Create user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def UpdateUser(self, request, context):
        """Update user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def DeleteUser(self, request, context):
        """Delete user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def ChangePassword(self, request, context):
        """Change password
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def VerifyUser(self, request, context):
        """Verify user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def UpdateUserStatus(self, request, context):
        """Update user status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details(_METHOD_NOT_IMPLEMENTED)
        raise NotImplementedError(_METHOD_NOT_IMPLEMENTED)


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=user__service__pb2.GetUsersRequest.FromString,
                    response_serializer=user__service__pb2.GetUsersResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=user__service__pb2.GetUserByIdRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=user__service__pb2.CreateUserRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=user__service__pb2.UpdateUserRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=user__service__pb2.DeleteUserRequest.FromString,
                    response_serializer=user__service__pb2.DeleteUserResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=user__service__pb2.ChangePasswordRequest.FromString,
                    response_serializer=user__service__pb2.ChangePasswordResponse.SerializeToString,
            ),
            'VerifyUser': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUser,
                    request_deserializer=user__service__pb2.VerifyUserRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'UpdateUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserStatus,
                    request_deserializer=user__service__pb2.UpdateUserStatusRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arcana.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arcana.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User Service - For Controller → Service communication

    """

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/GetUsers',
            user__service__pb2.GetUsersRequest.SerializeToString,
            user__service__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/GetUserById',
            user__service__pb2.GetUserByIdRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/CreateUser',
            user__service__pb2.CreateUserRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/UpdateUser',
            user__service__pb2.UpdateUserRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/DeleteUser',
            user__service__pb2.DeleteUserRequest.SerializeToString,
            user__service__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/ChangePassword',
            user__service__pb2.ChangePasswordRequest.SerializeToString,
            user__service__pb2.ChangePasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/VerifyUser',
            user__service__pb2.VerifyUserRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/UpdateUserStatus',
            user__service__pb2.UpdateUserStatusRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcana.UserService/HealthCheck',
            common__pb2.Empty.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
